/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  ERC1155BatchRecipient,
  ERC1155BatchRecipientInterface,
} from "../../../contracts/test/ERC1155BatchRecipient";

const _abi = [
  {
    inputs: [],
    name: "UnexpectedBatchData",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onERC1155BatchReceived",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610273806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063bc197c8114610030575b600080fd5b61004361003e366004610116565b610060565b6040516001600160e01b0319909116815260200160405180910390f35b6000815160001461008457604051631de805c760e31b815260040160405180910390fd5b5063bc197c8160e01b979650505050505050565b80356001600160a01b03811681146100af57600080fd5b919050565b60008083601f8401126100c657600080fd5b50813567ffffffffffffffff8111156100de57600080fd5b6020830191508360208260051b85010111156100f957600080fd5b9250929050565b634e487b7160e01b600052604160045260246000fd5b600080600080600080600060a0888a03121561013157600080fd5b61013a88610098565b965061014860208901610098565b9550604088013567ffffffffffffffff8082111561016557600080fd5b6101718b838c016100b4565b909750955060608a013591508082111561018a57600080fd5b6101968b838c016100b4565b909550935060808a01359150808211156101af57600080fd5b818a0191508a601f8301126101c357600080fd5b8135818111156101d5576101d5610100565b604051601f8201601f19908116603f011681019083821181831017156101fd576101fd610100565b816040528281528d602084870101111561021657600080fd5b8260208601602083013760006020848301015280955050505050509295989194975092955056fea2646970667358221220e74fa231f72c0b758b04c498511fe619ef3f8d24f15e07730a17ec24d1c1a44b64736f6c63430008110033";

type ERC1155BatchRecipientConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC1155BatchRecipientConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC1155BatchRecipient__factory extends ContractFactory {
  constructor(...args: ERC1155BatchRecipientConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ERC1155BatchRecipient> {
    return super.deploy(overrides || {}) as Promise<ERC1155BatchRecipient>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ERC1155BatchRecipient {
    return super.attach(address) as ERC1155BatchRecipient;
  }
  override connect(signer: Signer): ERC1155BatchRecipient__factory {
    return super.connect(signer) as ERC1155BatchRecipient__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC1155BatchRecipientInterface {
    return new utils.Interface(_abi) as ERC1155BatchRecipientInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC1155BatchRecipient {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC1155BatchRecipient;
  }
}
