/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  InvalidERC721Recipient,
  InvalidERC721RecipientInterface,
} from "../../../../contracts/test/InvalidERC721Recipient.sol/InvalidERC721Recipient";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610157806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063150b7a0214610030575b600080fd5b61004d61003e366004610086565b61abcd60f01b95945050505050565b6040516001600160e01b0319909116815260200160405180910390f35b80356001600160a01b038116811461008157600080fd5b919050565b60008060008060006080868803121561009e57600080fd5b6100a78661006a565b94506100b56020870161006a565b935060408601359250606086013567ffffffffffffffff808211156100d957600080fd5b818801915088601f8301126100ed57600080fd5b8135818111156100fc57600080fd5b89602082850101111561010e57600080fd5b969995985093965060200194939250505056fea2646970667358221220ed17695f9d15651568b96ecef7ed2f97eea746fb6755f6c6cac0d210a4c1eda064736f6c63430008110033";

type InvalidERC721RecipientConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: InvalidERC721RecipientConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class InvalidERC721Recipient__factory extends ContractFactory {
  constructor(...args: InvalidERC721RecipientConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<InvalidERC721Recipient> {
    return super.deploy(overrides || {}) as Promise<InvalidERC721Recipient>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): InvalidERC721Recipient {
    return super.attach(address) as InvalidERC721Recipient;
  }
  override connect(signer: Signer): InvalidERC721Recipient__factory {
    return super.connect(signer) as InvalidERC721Recipient__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): InvalidERC721RecipientInterface {
    return new utils.Interface(_abi) as InvalidERC721RecipientInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InvalidERC721Recipient {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as InvalidERC721Recipient;
  }
}
