/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type TransferHelperItemStruct = {
  itemType: PromiseOrValue<BigNumberish>;
  token: PromiseOrValue<string>;
  identifier: PromiseOrValue<BigNumberish>;
  amount: PromiseOrValue<BigNumberish>;
};

export type TransferHelperItemStructOutput = [
  number,
  string,
  BigNumber,
  BigNumber
] & {
  itemType: number;
  token: string;
  identifier: BigNumber;
  amount: BigNumber;
};

export type TransferHelperItemsWithRecipientStruct = {
  items: TransferHelperItemStruct[];
  recipient: PromiseOrValue<string>;
  validateERC721Receiver: PromiseOrValue<boolean>;
};

export type TransferHelperItemsWithRecipientStructOutput = [
  TransferHelperItemStructOutput[],
  string,
  boolean
] & {
  items: TransferHelperItemStructOutput[];
  recipient: string;
  validateERC721Receiver: boolean;
};

export interface TransferHelperInterface extends utils.Interface {
  functions: {
    "bulkTransfer(((uint8,address,uint256,uint256)[],address,bool)[],bytes32)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "bulkTransfer"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bulkTransfer",
    values: [
      TransferHelperItemsWithRecipientStruct[],
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "bulkTransfer",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TransferHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TransferHelperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bulkTransfer(
      items: TransferHelperItemsWithRecipientStruct[],
      conduitKey: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  bulkTransfer(
    items: TransferHelperItemsWithRecipientStruct[],
    conduitKey: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bulkTransfer(
      items: TransferHelperItemsWithRecipientStruct[],
      conduitKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    bulkTransfer(
      items: TransferHelperItemsWithRecipientStruct[],
      conduitKey: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bulkTransfer(
      items: TransferHelperItemsWithRecipientStruct[],
      conduitKey: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
